### ISSUE TITLE
Add sound support for queue notifications

### ISSUE THREAD

**Issue by haloflooder** [virustotalop/ProxyQueues#4]
When they move up in the queue, we can let the player know via sound.

Sound documentation for velocity:
![Velocity Player JavaDoc](https://jd.velocitypowered.com/1.1.0/com/velocitypowered/api/proxy/Player.html)
![Adventure Sound JavaDoc](https://jd.adventure.kyori.net/api/4.7.0/net/kyori/adventure/audience/Audience.html?is-external=true#playSound(net.kyori.adventure.sound.Sound))
![Adventure Example Code](https://docs.adventure.kyori.net/sound.html)

format:
```yml
notify:
  method:
  - BOSSBAR
  - TEXT
  - SOUND
  normal:
    actionbar:
      design: "Queued for {server}: {pos}"
    bossbar:
      design: "Queued for {server}: {pos}"
    text:
      design: "Queued for {server}: {pos}"
    title:
      title: Current in queue
      subtitle: "Position: {pos}
    sound:
      name: "block.note.harp"
      pitch: 1 # 0-2
      volume: 1 0-2
```
